# Generated by Django 4.2.3 on 2023-07-27 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='descriptipon',
            new_name='description',
        ),
    ]
