# Generated by Django 4.2.3 on 2023-07-27 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_alter_service_gallery_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='services', verbose_name='Картинка')),
                ('gallery', models.ManyToManyField(related_name='design_project_gallery', to='mainsite.image', verbose_name='Галерея')),
            ],
        ),
    ]
